//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace brigen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("brigen.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class modifier &apos;{0}&apos; specified multiple times..
        /// </summary>
        internal static string ClassModifierSpecifiedMultipleTimes {
            get {
                return ResourceManager.GetString("ClassModifierSpecifiedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected either token type &apos;{0}&apos; or &apos;{1}&apos;..
        /// </summary>
        internal static string ExpectedEitherTkOrTk {
            get {
                return ResourceManager.GetString("ExpectedEitherTkOrTk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected token of type &apos;{0}&apos;, but encountered an identifier instead..
        /// </summary>
        internal static string ExpectedTkButEncounteredIdentifier {
            get {
                return ResourceManager.GetString("ExpectedTkButEncounteredIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected token type &apos;{0}&apos;, but encountered &apos;{1}&apos; instead..
        /// </summary>
        internal static string ExpectedTkButEncounteredTk {
            get {
                return ResourceManager.GetString("ExpectedTkButEncounteredTk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get/set defined multiple times for property..
        /// </summary>
        internal static string GetSetDefinedMultipleTimes {
            get {
                return ResourceManager.GetString("GetSetDefinedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal compiler error occurred: {0}.
        /// </summary>
        internal static string InternalCompileError {
            get {
                return ResourceManager.GetString("InternalCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attribute &apos;{0}&apos; specified.
        /// </summary>
        internal static string InvalidAttribute {
            get {
                return ResourceManager.GetString("InvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A struct cannot contain a field of its own type..
        /// </summary>
        internal static string StructNoFieldOfOwnType {
            get {
                return ResourceManager.GetString("StructNoFieldOfOwnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct &apos;{0}&apos; does not declare any fields..
        /// </summary>
        internal static string StructNoFields {
            get {
                return ResourceManager.GetString("StructNoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined symbol &apos;{0}&apos; used..
        /// </summary>
        internal static string UndefinedSymUsed {
            get {
                return ResourceManager.GetString("UndefinedSymUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined symbol &apos;{0}&apos; used; did you mean &apos;{1}&apos;?.
        /// </summary>
        internal static string UndefinedSymUsed_WithSuggestion {
            get {
                return ResourceManager.GetString("UndefinedSymUsed_WithSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end-of-file encountered..
        /// </summary>
        internal static string UnexpectedEof {
            get {
                return ResourceManager.GetString("UnexpectedEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos; encountered..
        /// </summary>
        internal static string UnexpectedTk {
            get {
                return ResourceManager.GetString("UnexpectedTk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected top-level token &apos;{0}&apos; encountered..
        /// </summary>
        internal static string UnexpectedTopLevelTk {
            get {
                return ResourceManager.GetString("UnexpectedTopLevelTk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown class modifier &apos;{0}&apos; specified..
        /// </summary>
        internal static string UnknownClassModifier {
            get {
                return ResourceManager.GetString("UnknownClassModifier", resourceCulture);
            }
        }
    }
}
